#!/usr/bin/env bash
#
# Builds the mozc native pieces and stages them into the :mozc Gradle module.
#
# Two bazel invocations, not one, and that split is not incidental: mozc.data is an
# architecture-independent blob produced by host tools, and those host tools are marked
# incompatible under --config oss_android. Asking for both in a single command fails analysis.
#
# Outputs:
#   mozc/src/main/jniLibs/<abi>/libmozc.so
#   mozc/src/main/assets/mozc.data
#   mozc/src/main/proto/protocol/*.proto
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOZC_SRC="${ROOT}/third_party/mozc/src"
MODULE="${ROOT}/mozc/src/main"

if [[ ! -d "${MOZC_SRC}" ]]; then
  echo "error: ${MOZC_SRC} not found. Run: git clone --depth 1 https://github.com/google/mozc.git third_party/mozc" >&2
  exit 1
fi

BAZEL="${BAZEL:-$(command -v bazelisk || command -v bazel)}"
PYTHON="${PYTHON:-python3}"

cd "${MOZC_SRC}"

# Patches against upstream. third_party/mozc is otherwise a pristine checkout, so anything we need
# to change there lives in patches/ and is re-applied here. `git apply --check` first so a re-run
# on an already-patched tree is a no-op rather than an error.
for patch in "${ROOT}"/patches/*.patch; do
  [[ -e "${patch}" ]] || continue
  if git -C "${ROOT}/third_party/mozc" apply --check "${patch}" 2>/dev/null; then
    echo "==> Applying $(basename "${patch}")"
    git -C "${ROOT}/third_party/mozc" apply "${patch}"
  else
    echo "==> $(basename "${patch}") already applied"
  fi
done

# Generated by scripts/gen_flick_layout.py from the layout that ships, and consumed by the patched
# typing corrector. Copied rather than patched so regenerating the layout is enough to update it.
if [[ -f "${ROOT}/patches/flick_geometry.inc" ]]; then
  install -m 644 "${ROOT}/patches/flick_geometry.inc" "${MOZC_SRC}/engine/flick_geometry.inc"
fi

# The bundled dictionaries go into the system dictionary, so they must be in place before bazel
# reads the dictionary sources. Generated rather than committed: the inputs are fetched by
# scripts/fetch_dictionaries.sh and are far too large to keep in the repository.
if compgen -G "${ROOT}/third_party/dictionaries/*.txt" > /dev/null; then
  echo "==> Generating dictionary10.txt from the bundled dictionaries"
  "${PYTHON}" "${ROOT}/scripts/gen_system_dictionary.py" \
    > "${MOZC_SRC}/data/dictionary_oss/dictionary10.txt"
else
  echo "==> No bundled dictionaries; writing an empty dictionary10.txt"
  : > "${MOZC_SRC}/data/dictionary_oss/dictionary10.txt"
fi

if [[ ! -d third_party/ndk ]]; then
  echo "==> Fetching mozc build dependencies (Android NDK r29)"
  "${PYTHON}" build_tools/update_deps.py
fi

echo "==> Building libmozc.so for all ABIs"
"${BAZEL}" build package --config oss_android --config release_build

echo "==> Building mozc.data (host config)"
"${BAZEL}" build //data_manager/oss:mozc.data --config oss_linux --config release_build

echo "==> Staging native libraries"
rm -rf "${MODULE}/jniLibs"
mkdir -p "${MODULE}/jniLibs"
unzip -q -o bazel-bin/android/jni/native_libs.zip -d "${MODULE}/jniLibs.tmp"
mv "${MODULE}/jniLibs.tmp/libs"/* "${MODULE}/jniLibs/"
rm -rf "${MODULE}/jniLibs.tmp"

echo "==> Staging mozc.data"
mkdir -p "${MODULE}/assets"
install -m 644 bazel-bin/data_manager/oss/mozc.data "${MODULE}/assets/mozc.data"

echo "==> Staging protocol buffers"
# protoc resolves `import "protocol/config.proto"` relative to the source root, so the protos have
# to keep their protocol/ prefix inside the module's proto source set.
rm -rf "${MODULE}/proto/protocol"
mkdir -p "${MODULE}/proto/protocol"
install -m 644 protocol/*.proto "${MODULE}/proto/protocol/"

echo
echo "Done."
du -sh "${MODULE}/jniLibs" "${MODULE}/assets/mozc.data"
